# Generated by Django 3.2.7 on 2021-09-10 19:51

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2021, 9, 10, 19, 51, 4, 677563, tzinfo=utc
                        )
                    ),
                ),
                (
                    "finish_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2021, 9, 10, 19, 51, 4, 677627, tzinfo=utc
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Only_text_answer"),
                            ("one_choice", "Answer with one choice"),
                            ("many_choice", "Answer with many choices"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="ask_type",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_asks",
                        to="quiz.quiz",
                    ),
                ),
            ],
        ),
    ]
