# Generated by Django 3.2.7 on 2021-09-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="finish_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
