# Generated by Django 3.2.7 on 2021-09-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_auto_20210911_0814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="ask",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ask",
                to="quiz.ask",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="quiz",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="quiz.quiz",
            ),
        ),
    ]
