# Generated by Django 3.2.7 on 2021-09-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_auto_20210911_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="quiz.quiz",
            ),
        ),
    ]
